# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2"

required_plugins = %w( vagrant-vbguest )
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

required_plugins = %w( vagrant-hostmanager )
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end
Vagrant.configure("2") do |config|
  
  config.vm.box = "nrel/CentOS-6.7-x86_64"

  config.ssh.forward_agent = true
  config.ssh.shell = "bash -l" 
  
  config.vm.synced_folder "../ansible", "/ansible"

  config.vm.synced_folder "../shared/web", "/var/www/myproject"
  
  config.vm.provision :shell, path: "shell/vagrant_main_provision.sh"

  config.vm.define 'apache' do |node|

    node.vm.network :forwarded_port, guest: 80, host: 8080
    node.vm.network :private_network, ip: "192.168.33.99"
    node.vm.hostname = "myMpwar"
    node.hostmanager.aliases = %w("myMpwar.dev" "myMpwar.prod")
  end
  
   config.vm.define 'apache_futuro1' do |node|

    node.vm.network :forwarded_port, guest: 81, host: 8081
    node.vm.network :private_network, ip: "192.168.33.100"
    node.vm.hostname = "myMpwar"
    node.hostmanager.aliases = %w("myMpwar.dev" "myMpwar.prod")
    node.vm.provision :shell, path: "shell/vagrant_main_provision_apache.sh"
  end

   config.vm.define 'apache_futor2' do |node|

    node.vm.network :forwarded_port, guest: 82, host: 8082
    node.vm.network :private_network, ip: "192.168.33.101"
    node.vm.hostname = "myMpwar"
    node.hostmanager.aliases = %w("myMpwar.dev" "myMpwar.prod")
    node.vm.provision :shell, path: "shell/vagrant_main_provision_apache.sh"
  end

   config.vm.define 'mysql_futuro1' do |node|

    node.vm.network :forwarded_port, guest: 83, host: 8083
    node.vm.network :private_network, ip: "192.168.33.102"
    node.vm.hostname = "myMpwar"
    node.hostmanager.aliases = %w("myMpwar.dev" "myMpwar.prod")
    node.vm.provision :shell, path: "shell/vagrant_main_provision_mysql.sh"
  end

   config.vm.define 'mysql_futuro2' do |node|

    node.vm.network :forwarded_port, guest: 84, host: 8084
    node.vm.network :private_network, ip: "192.168.33.103"
    node.vm.hostname = "myMpwar"
    node.hostmanager.aliases = %w("myMpwar.dev" "myMpwar.prod")
    node.vm.provision :shell, path: "shell/vagrant_main_provision_mysql.sh"
  end

end
