---
- name: Server Config LAMP
  hosts: "webservers"
  become: true
  become_user: root
  roles:
    - role: geerlingguy.ntp
      ntp_timezone: Europe/Madrid

    - { role: geerlingguy.apache }
    - { role: geerlingguy.firewall }

    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'

    - { role: geerlingguy.php-versions }
    - { role: geerlingguy.php }
    - { role: geerlingguy.composer }

  tasks:

    - name: Create directory
      file: path=/var/www/myproject state=directory


    - name: Create index.php
      template: src=templates/index.php dest=/var/www/myproject/index.php

    - name: Create phpinfo();
      template: src=templates/info.php dest=/var/www/myproject/info.php